use_frameworks!

target 'BFDisplayEvent_Example' do
  pod 'BFDisplayEvent', :path => '../'

  target 'BFDisplayEvent_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
